name: trancaominhthang_205051813
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  api_cache_manager: ^1.0.2
  intl: any
  flutter_localizations:
    sdk: flutter
  badges: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_localizations:
    sdk: flutter
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
